/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-compliance': RouteRecordInfo<'admin-compliance', '/admin/compliance', Record<never, never>, Record<never, never>>,
    'auth-mfa-login': RouteRecordInfo<'auth-mfa-login', '/auth/mfa-login', Record<never, never>, Record<never, never>>,
    'auth-verify-email': RouteRecordInfo<'auth-verify-email', '/auth/verify-email', Record<never, never>, Record<never, never>>,
    'bulk-sign': RouteRecordInfo<'bulk-sign', '/bulk-sign', Record<never, never>, Record<never, never>>,
    'change-password': RouteRecordInfo<'change-password', '/change-password', Record<never, never>, Record<never, never>>,
    'documents': RouteRecordInfo<'documents', '/documents', Record<never, never>, Record<never, never>>,
    'documents-id': RouteRecordInfo<'documents-id', '/documents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'prepare-id': RouteRecordInfo<'prepare-id', '/prepare/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'settings-delegations': RouteRecordInfo<'settings-delegations', '/settings/delegations', Record<never, never>, Record<never, never>>,
    'sign-token': RouteRecordInfo<'sign-token', '/sign/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'sign-declined': RouteRecordInfo<'sign-declined', '/sign/declined', Record<never, never>, Record<never, never>>,
    'sign-success': RouteRecordInfo<'sign-success', '/sign/success', Record<never, never>, Record<never, never>>,
    'signatures': RouteRecordInfo<'signatures', '/signatures', Record<never, never>, Record<never, never>>,
    'templates': RouteRecordInfo<'templates', '/templates', Record<never, never>, Record<never, never>>,
    'templates-id': RouteRecordInfo<'templates-id', '/templates/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-id-bulk': RouteRecordInfo<'templates-id-bulk', '/templates/:id/bulk', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-id-edit': RouteRecordInfo<'templates-id-edit', '/templates/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-id-use': RouteRecordInfo<'templates-id-use', '/templates/:id/use', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'templates-create': RouteRecordInfo<'templates-create', '/templates/create', Record<never, never>, Record<never, never>>,
    'templates-new': RouteRecordInfo<'templates-new', '/templates/new', Record<never, never>, Record<never, never>>,
    'upload': RouteRecordInfo<'upload', '/upload', Record<never, never>, Record<never, never>>,
  }
}
