/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-compliance': RouteRecordInfo<'admin-compliance', '/admin/compliance', Record<never, never>, Record<never, never>>,
    'documents': RouteRecordInfo<'documents', '/documents', Record<never, never>, Record<never, never>>,
    'documents-id-parent': RouteRecordInfo<'documents-id-parent', '/documents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-id': RouteRecordInfo<'documents-id', '/documents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'prepare-id': RouteRecordInfo<'prepare-id', '/prepare/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'settings-delegations': RouteRecordInfo<'settings-delegations', '/settings/delegations', Record<never, never>, Record<never, never>>,
    'sign-token': RouteRecordInfo<'sign-token', '/sign/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'sign-declined': RouteRecordInfo<'sign-declined', '/sign/declined', Record<never, never>, Record<never, never>>,
    'sign-success': RouteRecordInfo<'sign-success', '/sign/success', Record<never, never>, Record<never, never>>,
    'signatures': RouteRecordInfo<'signatures', '/signatures', Record<never, never>, Record<never, never>>,
    'templates': RouteRecordInfo<'templates', '/templates', Record<never, never>, Record<never, never>>,
    'templates-create': RouteRecordInfo<'templates-create', '/templates/create', Record<never, never>, Record<never, never>>,
    'upload': RouteRecordInfo<'upload', '/upload', Record<never, never>, Record<never, never>>,
  }
}
