version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: esign-app-prod:latest
    container_name: esign_app_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080" # Reverb
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://esign.sadcpf.org
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: sadc_esign
      DB_USERNAME: sadc_esign
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - esign-prod-network

  db:
    image: postgres:15-alpine
    container_name: esign_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: sadc_esign
      POSTGRES_USER: sadc_esign
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data_prod_v2:/var/lib/postgresql/data
    networks:
      - esign-prod-network

  redis:
    image: redis:alpine
    container_name: esign_redis_prod
    restart: unless-stopped
    networks:
      - esign-prod-network

networks:
  esign-prod-network:
    driver: bridge

volumes:
  pg_data_prod_v2:
