[supervisord]
nodaemon=true
user=root

[program:php]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www/html/backend
autostart=true
autorestart=true
stderr_logfile=/var/www/html/backend/storage/logs/php-error.log
stdout_logfile=/var/www/html/backend/storage/logs/php-out.log

[program:queue]
command=php artisan queue:work --tries=3
directory=/var/www/html/backend
autostart=true
autorestart=true
stderr_logfile=/var/www/html/backend/storage/logs/queue-error.log
stdout_logfile=/var/www/html/backend/storage/logs/queue-out.log

[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/html/backend
autostart=true
autorestart=true
stderr_logfile=/var/www/html/backend/storage/logs/reverb.log
stdout_logfile=/var/www/html/backend/storage/logs/reverb.log

[program:npm]
command=npm run dev -- --host
directory=/var/www/html/frontend
autostart=true
autorestart=true
stderr_logfile=/var/www/html/backend/storage/logs/npm-error.log
stdout_logfile=/var/www/html/backend/storage/logs/npm-out.log
